### ISSUE TITLE
'pvals' not a valid field

### ISSUE THREAD

**Issue by jpalowitch** [jpalowitch/corvars#2]
After commit bf8ec917b6775635ec5665dffc3ba30d1ed3f1bb the script bmdupdate_test.R gives:

    Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 'pvals' is not a valid field or method name for reference class "Rcpp_BmdUpdater"

**Comment by miheerdew** [comment]
Did you pull the latest bmdupdater package (and build it?)

**Comment by jpalowitch** [comment]
I did not. Thanks.
